# Generated by Django 3.2.5 on 2021-07-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_credentials_webiste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='webiste',
            new_name='website',
        ),
    ]
