# Generated by Django 3.2.5 on 2021-07-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_credentials_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.TextField(),
        ),
    ]
