# Generated by Django 3.2.5 on 2021-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_credentials_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.BinaryField(),
        ),
    ]
